### PR TITLE
feature: added sqlite. Fixes #19

### LINKED ISSUE #19: Add sqlite driver as a dependency
This change is needed in order to have a gitpod setup for tower and groundswell where the latter use the sqlite driver to perform the migration

### PR DESCRIPTION
**Pull request by swampie**
This PR adds the drivers and the support for sqlite databases

### CODE REVIEW

**Review by tcrespog — APPROVED** [review]

**Comment by pditommaso** [comment]
This is nice. What about adding a test for the binary version [like this](http://github.com/seqeralabs/migtool/blob/0a1d13300d62666d956e404b5ea0f1f6100fd9e8/src/nativeCliTest/groovy/io/seqera/migtool/MysqlTest.groovy#L28-L53) so we are sure the compile version works?

**Review by jorgeaguileraseqera — APPROVED** [review]

**Comment by pditommaso** [comment]
> Task :nativeCliTest
>
> SqliteTest > should run native binary FAILED
    java.lang.ArrayStoreException at SqliteTest.groovy:33

**Comment by swampie** [comment]
I love GraalVM

**Comment by jorgeaguileraseqera** [comment]
It's not a graalvm error,

change this line
```--url', "jdbc:sqlite:${this.dbName}" ```
by 

`'--url', "jdbc:sqlite:${this.dbName}".toString(),`

**Comment by jorgeaguileraseqera** [comment]
also, I don't know why, you need to specify the driver ( `'--driver','org.h2.Driver',`) in command-line arguments

maybe we are missing to include some dependency

**Comment by pditommaso** [comment]
Actually it should be needed. sqlite should be added here 

http://github.com/seqeralabs/migtool/blob/0a1d13300d62666d956e404b5ea0f1f6100fd9e8/src/main/java/io/seqera/migtool/Helper.java#L204-L218

**Comment by pditommaso** [comment]
The graal guru strike again 😄

**Comment by jorgeaguileraseqera** [comment]
stackoverflow superpower

btw I founded we're initilizing the dialect to `mysql` always

**Comment by pditommaso** [comment]
> btw I founded we're initilizing the dialect to mysql always

What do you mean?

**Comment by jorgeaguileraseqera** [comment]
sorry:

at https://github.com/seqeralabs/migtool/pull/20/files#diff-d5a5ef22be862b9bb4e634ed65a40cfda20d8302fd85b238519a9aecb2607601R32

we init the dialect by the default to `mysql` so if not set by command line we use `mysql` and never extracted from the url

**Comment by swampie** [comment]
Is this version releasable? @pditommaso

**Review by pditommaso — APPROVED** [review]

**Pull request merged**
