### PR TITLE
Bump to version 1.6.0

### PR DESCRIPTION
**Pull request by tcrespog**
- Bump to 1.6.0 with the aim of creating a release that includes https://github.com/seqeralabs/migtool/pull/49.

### CODE REVIEW

**Review by pditommaso — CHANGES_REQUESTED** [review]
Worth updating the changelog correspondingly

**Review by pditommaso — APPROVED** [review]
Nice

**Comment by tcrespog** [comment]
Hi, @pditommaso. The `[release]` [build](https://github.com/seqeralabs/migtool/actions/runs/10918785826) worked successfully, but is there anything else necessary in order to publish the artifact to the Maven repo?

**Comment by pditommaso** [comment]
Think it was never added to the CI build. I run `./gradlew publish`, not it should be ok

**Comment by tcrespog** [comment]
> Think it was never added to the CI build. I run `./gradlew publish`, not it should be ok

Thank you.

**Pull request merged**
