### PR TITLE
bumping sqllite version

### PR DESCRIPTION
**Pull request by swampie**
Reopening this because of wrong merge.

### CODE REVIEW

**Comment by swampie** [comment]
> DId test pass? @pditommaso 
Yes

**Comment by swampie** [comment]
image

**Comment by alvaromartmart** [comment]
I don't understand why the gha workflow is not being triggered:
https://github.com/seqeralabs/migtool/blob/22df742439ec35cbd375c55973f56caf6f120509/.github/workflows/build.yml#L1-L10
the commits don't contain `[ci skip]` either. This is weird

**Comment by alvaromartmart** [comment]
> I don't understand why the gha workflow is not being triggered:
> 

actually... please check something @swampie: your commits don't show up as `verified`, maybe this repo is configured not to run Github Actions for unverified commits?

**Comment by tcrespog** [comment]
> > I don't understand why the gha workflow is not being triggered:
> 
> actually... please check something @swampie: your commits don't show up as `verified`, maybe this repo is configured not to run Github Actions for unverified commits?

I believe this is due to the branch name containing `/`.

I think this should be `**` for it to work:
https://github.com/seqeralabs/migtool/blob/d1d6ba2c4f7b0cc85c6100696a254d0ea68d4821/.github/workflows/build.yml#L7

**Comment by pditommaso** [comment]
@tcrespog yeah, you are right

**Review by pditommaso — APPROVED** [review]

**Comment by pditommaso** [comment]
Is a release needed for this?

**Pull request merged**
