### PR TITLE
Notask/updates micronaut version to 4.2.3

### PR DESCRIPTION
**Pull request by pgeadas**
- Updates the micronaut version to 4

## Guidelines for testing

- Every test is still green and the output of the test run is pretty much identical to the one using  micronaut 2

### CODE REVIEW

**Comment by pditommaso** [comment]
Tests didn't run?

**Comment by pgeadas** [comment]
> Tests didn't run?

Do I need to use a tag in the comments to trigger them?

**Comment by pditommaso** [comment]
No. I believe they are not running because there's a `/` in the branch name

**Comment by pgeadas** [comment]
Closed in favour of #37

**Pull request closed without merging**
